//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librerias
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectolibreriaEntities : DbContext
    {
        public proyectolibreriaEntities()
            : base("name=proyectolibreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VVentasXCliente> VVentasXCliente { get; set; }
        public virtual DbSet<VLibroCategoria> VLibroCategoria { get; set; }
    }
}
