//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librerias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public string Rut { get; set; }
        public string ISBN { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
