//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librerias
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVentasXCliente
    {
        public string Rut { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Titulo { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
